### ISSUE TITLE
Peptide Shaker 1.5.0: Import of X! Tandem Results

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#80] opened 2016-01-22 22:55 UTC
Hey folks,

first PS 1.5.0 thingy (a bit following up on the issue #121): after import of my GluC X! Tandem results (which had not worked in 1.4.0) nearly half of my PSMs have a ppm error of <<-20ppm. after closer inspection, it is always peptides with  an N-terminal TMT and at at least TWO fixed modifications (TMT@K or cmCys) present. It seems that as soon as TWO TMT@K are present, the N-terminal TMT is not taken into account anymore.

PS: I did not rerun my X! Tandem searches in the new SearchGUI. Do I have to?
PPS: In general there is going something wrong with this import, as I end up with 2400 PSMs pointing towards TMT@Nter, whereas Comet, MSGF+, and MsAmanda find only 50-100 (Note: it is a preTAILS sample so is NOT enriched for N-termini).

**Comment by hbarsnes** [comment] 2016-01-23 01:53
You don't have to redo the X!Tandem searches as the only change here is in the parsing. But if you send me the X!Tandem results file (plus search settings, mgf and FASTA files, preferably all in one zip file) I'll try to figure out what the problem is. I think I have an idea already. If you could also provide the peptide sequence of one of the cases where it seems to go wrong that would be great.

**Comment by ulriche** [comment] 2016-01-23 01:58
will put something together - but will take a bit.
I also double checked the ArgC results - and also there it is PSMs with an
N-terminal TMT and 2 TMTs at "K".

but the really strange thing is, that in the last PeptideShaker (1.4.0) I
got something like 5936 PSMs, and now (1.5.0) it is only 2328 - from the
same X! Tandem result file.
will double check that and then put everything together.

cheers
u

**Comment by hbarsnes** [comment] 2016-01-23 03:01
It's not that strange after all I think. When trying to fix the issue with the fixed and variable TMT tags on the same peptide in the X!Tandem output, I ended up only allowing one fixed PTM of each type per peptide, instead of one per residue. Should be fixed in the beta version below. So give it a go and let me know if you find any other issues.

https://www.dropbox.com/s/aknwvcjd3iadphu/PeptideShaker-1.5.1-beta.zip?dl=0

**Comment by ulriche** [comment] 2016-01-23 03:03
will give it a go right away ... but I am a bit slow today - too many
distractions! :-)

**Comment by ulriche** [comment] 2016-01-23 03:50
we are back in the race! whoop whoop!

exactly same results as with Peptide Shaker 1.4.0 but without crazy ppms.

**Comment by ulriche** [comment] 2016-01-23 04:16
but just a small observation ... I searched with plus/minus 15ppm and now I have 9 hits between plus 15 and 19ppm. so I tried to redo the math, and I guess I use slightly different values than you do, but here my magic math:

m/z = 631.28313 and the charge 2+   ->   (631.28313*2)-(2*1.007273) = 1260.5517

the PSM was identified with an Isotope error of "1", thus   -> 1260.5517-1.007273 = 1259.5444

the theoretical mass is given as:
1259.52658841083; thus   -> (1259.5444-1259.5266)/(1259.5266)*1000000 = 14.17 ppm

but PeptideShaker gives me ***17.25177 ppm***. possible? but maybe my math is just plain wrong.

**Comment by ulriche** [comment] 2016-01-23 05:10
but think otherwise the beta version works perfect so far

**Comment by ulriche** [comment] 2016-01-23 06:43
and guess it is my math somehow, as for Comet it perfectly works out. maybe you spot the error right away ...

**Comment by hbarsnes** [comment] 2016-01-23 13:37
> but PeptideShaker gives me 17.25177 ppm. possible?

I notice two things. First, the isotope error is one neutron and not one proton isn't it? So 1.008664916 instead of 1.007276466812.

Second, I get a ppm around 17 if I add the neutron to the theoretical mass instead of subtracting it from the experimental mass. I have to look into which if the two makes the most sense though. And in any case we ought to be consistent.

**Comment by ulriche** [comment] 2016-01-23 17:31
ha-ha ... yeah, of course. rookie mistake. but wondering now if XTandem
does the same ... but can't imagine. thanks for clarification!

**Comment by ulriche** [comment] 2016-01-23 19:27
redid it now with the neutron ... and yep, then I end up perfectly in the plus/minus 15 ppm range 

my formula is now: {[(m/z*charge)-(charge*1.007273)-(isotope-number x 1.008664916)] - (theoretical mass)} x 1000000 ... guess that is how X! Tandem is doing it, whereas comet is doing it your way maybe - but for me it doesn't make that big of a difference if I add the neutron to the theoretical mass or if I subtract it from the experimental one ...

**Comment by mvaudel** [comment] 2016-01-23 19:34
Hi Ulrich,

Note that the ppm error is the error of the measurement, so it should be
calculated on the m/z value and not on the mass. This might explain the
difference :)

Best regards,

Marc

2016-01-23 5:16 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment] 2016-01-23 19:45
haha ... definitely true ... will try again ...

hmmm ... still not getting there ... but maybe another error on my side ...

**Comment by mvaudel** [comment] 2016-01-23 19:49
As for the mass of the isotope, we consider that these are C13 isotopes,
the mass we subtract is thus C13-C12, so obviously a bit less than a
neutron :) Does not make much of a difference though unless you work with
very high resolution though...

2016-01-23 20:45 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment] 2016-01-23 19:49
i attach my excel file ... if you have time to shed some light I would be more than happy. pretty sure I just do another stupid error ... 

[XTa_ppm-error_v01.xlsx](https://github.com/compomics/searchgui/files/102002/XTa_ppm-error_v01.xlsx)

**Comment by mvaudel** [comment] 2016-01-23 20:00
You need to divide by the theoretical mass and not the experimental :) I
get almost the exact same values as the ones in the ppm column.



2016-01-23 20:49 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment] 2016-01-23 20:11
crazy ... so the deal breaker is really using the mass of a neutron (as I thought I have to - but initially even used a proton; 1.008664916) or the difference of C12 and C13 (1.0033548378).

guess as you math works perfectly for comet, it is also the way Jimmy does it, but maybe Ron uses the neutron mass for X! Tandem.

**Comment by ulriche** [comment] 2016-01-23 20:16
but anyhow ... learned how to calculate it porperly - appreciated! :-)

**Comment by ulriche** [comment] 2016-01-23 22:22
but why is the difference between C12 and C13 not the mass of a neutron (1.008664916)? and why is C14 only 2.003241989 away? I am definitely missing something ...

**Comment by ulriche** [comment] 2016-01-23 23:53
ok ... got it now ... forgot about the "mass defect" - that stuff I learned/read by for too long ago! ;-)

**Comment by mvaudel** [comment] 2016-01-24 10:50
also missed a lot of high school classes ;)

2016-01-23 23:22 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Closed** 2016-01-25 15:06 UTC
Labels: bug
