### ISSUE TITLE
PeptideShaker cancels search when it is almost finished

### ISSUE THREAD

**Issue by SimionKreimer** [compomics/searchgui#61] opened 2015-10-01 05:31 UTC
Hi I have this issue in Windows 8 and on my archlinux laptop and it's been happening since Search GUI 2.0.5 (the first version I used). I've been trying to execute a MS-GF+ with PeptideShaker search for a few days now. Essentially everything seems to be working fine until almost the end of the analysis when PeptideShaker abruptly closes and the read out says the search was cancelled, Peptide Shaker failed ,and to check the PeptideShaker log. I've copied the PeptideShaker.log output (couldn't upload the log file for some reason).Please help!

Best, Simion

Thu Oct 01 00:31:15 EDT 2015: PeptideShaker version 1.0.6.
Memory given to the Java virtual machine: 11453595648.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 105509776.
Java version: 1.8.0_60.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "," at line 1, column 87.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(Unknown Source)
	at com.compomics.util.db.ObjectsDB.deleteObject(ObjectsDB.java:1040)
	at com.compomics.util.experiment.identification.IdentificationDB.removeProteinMatch(IdentificationDB.java:317)
	at com.compomics.util.experiment.identification.Identification.removeProteinMatch(Identification.java:925)
	at eu.isas.peptideshaker.protein_inference.ProteinInference.retainBestScoringGroups(ProteinInference.java:400)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:428)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:523)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:155)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:226)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:710)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:179)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1027)
Caused by: java.sql.SQLException: Syntax error: Encountered "," at line 1, column 87.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 20 more
Caused by: ERROR 42X01: Syntax error: Encountered "," at line 1, column 87.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 14 more
Free memory: 3634989344

**Comment by mvaudel** [comment] 2015-10-01 05:43
Dear Simion,

This is a rather cryptic error message, and there is no obvious solution as
far as I can see. It seems that the interaction with the back-end fails due
to an unexpected ",". Would it be possible for you to share the data with
us so that we can try to reproduce it on our side? We would need the mgf,
fasta, and searchGUI output.

Best regards and our apologizes for the inconvenience.

Marc

2015-10-01 7:31 GMT+02:00 SimionKreimer <notifications@github.com>:

**Comment by SimionKreimer** [comment] 2015-10-01 06:51
Hi Marc,
Thank you very much for the quick response. Here is a dropbox link with the materials you've requested:
https://www.dropbox.com/sh/w2z4gtouqa9derf/AACf_ctN72JRPkMeFfgbPZida?dl=0

Let me know if you have any issues with access, seems to work on my end.
Good luck!

**Comment by hbarsnes** [comment] 2015-10-01 20:23
Hi Simion,

Could you also send us the search parameter file you are using for the search? As then we could redo the search on our and try to reproduce the issue.

Best regards.
Harald

**Comment by SimionKreimer** [comment] 2015-10-01 21:06
Hi Harald,
Thank you for the quick response I've added the searchgui_out.zip to the Dropbox folder. As I understand it contains the .par file used for the search and the mzID file generated by MS-GF+. Thank you for your help, let me know if there's anything else I can do.

Best, Simion

**Comment by hbarsnes** [comment] 2015-10-01 22:11
Hi Simion,

Thanks for the files. I'll try to reproduce the issue and get back to you.

In any case, I recommend that you update to the just released new versions of both SearchGUI and PeptideShaker. Not that I think it will affect the issue with the ",". But it does fix some other issues that could occur regarding the search parameters.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2015-10-02 03:07
Hi Simion,

I can confirm that I can reproduce the issue on my side with your files. I'll try to come up with a fix and get back to you.

The problem is most likely your custom FASTA headers. I'd recommend using a simple search and replace (">" with ">generic|") in order to adhere to our non-standard FASTA format (http://compomics.github.io/searchgui/wiki/databasehelp.html#non-standard-fasta).

For example:
>XP_007625512.1|625268009 PREDICTED: thymosin beta-10 [Cricetulus griseus]
becomes
>generic|XP_007625512.1|625268009 PREDICTED: thymosin beta-10 [Cricetulus griseus]

We'd then use "XP_007625512.1" as the accession number, and "625268009 PREDICTED: thymosin beta-10 [Cricetulus griseus]" as the description. I think that makes sense?

Without the generic tag we're left with using the whole header as the accession number, which I think is what ultimately leads to the error.

Note that after changing the original database, you'll have to re-add the decoys and redo the search.

Let me know if this solve the problem.

Best regards,
Harald

**Comment by SimionKreimer** [comment] 2015-10-02 04:37
I can no longer import the fasta file after I add the generic marker as
you've instructed. The software simply says that there was an error without
clarification. I've added the modified fasta to the dropbox, just in case
I'm missing something.

Best, Simion

**Comment by hbarsnes** [comment] 2015-10-02 09:05
Hi Simion,

The problem was that the replacement resulted in non-unique accession numbers, indicated by "sw" becoming an accession number. So do another search and replace: ">generic|sw|" with ">generic|" and you should be able to import the file.

I've updated the code to display a better error message when this happens. This will be included in the next release.

Best regards,
Harald

**Comment by SimionKreimer** [comment] 2015-10-02 16:04
Hi Harald,
I didn't realize there were all these sw| entries in the database, and thank you for clearing that up. After this second modification, everything worked beautifully. Thank you for all your help and for making this excellent resource available.

Best, Simion

**Comment by hbarsnes** [comment] 2015-10-02 16:19
Hi Simion,

Happy to help. Especially when it all works out in the end. :)

Let is know if you come across any other issues.

Best regards,
Harald

**Closed by hbarsnes** 2015-10-02 16:19 UTC
