### ISSUE TITLE
SearchGUI wants to add missing charges

### ISSUE THREAD

**Issue by akwalker** [compomics/searchgui#140] opened 2017-02-23 21:56 UTC
A recent change to our instrument method is giving me some peaklists without charge states. SearchGUI catches this and wants to write in a list of default charges. I tell it to go ahead and the search proceeds fine. 

If I do another search on the same mgf file, it gives me the same option to replace the charges but then tells me that it can't delete the original spectrum file and won't add it to the search window. I tried deleting the cui files and anything else it created the first time, but get the same error. 

Now I can't get a second search to run on that mgf file. Can you give me a suggestion what I can do so I can perform a search more than once? 

I have the files on a D: drive with no security features limiting access to the files. It always works once, then never again on the same file.

**Comment by hbarsnes** [comment] 2017-02-24 20:44
Thanks for telling us about this. I'm not able to reproduce it on my side though. (Well, not unless I have the original mgf file opened in another program such that it cannot be deleted.) Are you closing SearchGUI in between the two searches or is this one continues run of SearchGUI? It should not matter, but you could try restarting SearchGUI before doing the second search to see if that solves the problem?

In any case, if you get asked to add the charges twice for the same file the charges are most likely not added correctly the first time or the process is not completed. Is there anything in the SearchGUI log file that can shed some light on what is happening?

BTW, which search engines are you using for the searches?

**Comment by hbarsnes** [comment] 2017-03-10 23:19
Given that we didn't hear back from you I assume you managed to resolve this issue? If this is not the case, please let us know and we'll reopen the issue.

**Closed by hbarsnes** 2017-03-10 23:19 UTC
Labels: help wanted
