### ISSUE TITLE
Processing identification files with PeptideShaker.

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/searchgui#309] opened 2021-07-20 05:54 UTC
SearchGUI 4.0.41 is stuck on this step (Processing identification files with PeptideShaker) since yesterday. I am using a 8core Tyrone CPU (32GB). I fed 6 .RAW files as input (I ain't sure if that okay to do) generated from a QExactive. PFA the report and screenshot. 
[20.7.21.txt](https://github.com/compomics/searchgui/files/6845783/20.7.21.txt)
![Status_20 07 21](https://user-images.githubusercontent.com/47975001/126268733-234130b4-3739-4b82-b50a-bbcbfa3ecee2.png)

**Comment by vipulbatra1985** [comment] 2021-07-20 09:28
Also, when I preformed a second search, despite the completion I received an error message stating "Peptide Shaker file (D:\Output_salt_ctrl\PeptideShaker-output.psdb) not found!"

**Comment by hbarsnes** [comment] 2021-07-21 21:10
As the error happens in PeptideShaker (and not in SearchGUI itself) you need to look into the PeptideShaker log file. You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report.

You can also try loading the searched data directly in PeptideShaker to see if that makes a difference.

**Comment by vipulbatra1985** [comment] 2021-07-23 09:55
When I try to open the searchgui_out.zip using PeptideShaker, I get a prompt that says ," No peptide shaker project was found in the zip file." PFA the reports. 
[PeptideShaker 2.0.33 log.txt](https://github.com/compomics/searchgui/files/6867131/PeptideShaker.2.0.33.log.txt)

**Comment by hbarsnes** [comment] 2021-07-23 11:26
It seems like PeptideShaker is having problems processing the data due to memory issues. Can you try increasing the memory provided to PeptideShaker and loading the data again? No need to research the data, but you will have to reprocess it in PeptideShaker.

You can increase the memory via the PeptideShaker Welcome dialog > Settings & Help > Settings > Java Settings.

**Comment by vipulbatra1985** [comment] 2021-07-23 11:44
I have doubled the allocated memory, nevertheless, the same result: When I try to open the searchgui_out.zip using PeptideShaker, I get a prompt that says ," No peptide shaker project was found in the zip file."

**Comment by hbarsnes** [comment] 2021-07-23 16:14
The file searchgui_out.zip indeed does not contain any PeptideShaker project. It is simply a zip file with the search results from the individual search engines ran via SearchGUI. To open such a zip file in PeptideShaker you need to select the "New Project" option, not the "Open Project" option.

**Comment by vipulbatra1985** [comment] 2021-07-24 07:31
The import process halted in between and could not complete since an error occurred ,"An error occurred: Cannot assign field "edited" because "obj" is null."

[PeptideShaker 2.0.33 log.txt](https://github.com/compomics/searchgui/files/6872071/PeptideShaker.2.0.33.log.txt)
[report_peptide shaker.txt](https://github.com/compomics/searchgui/files/6872072/report_peptide.shaker.txt)
[report_peptide shaker.txt](https://github.com/compomics/searchgui/files/6872073/report_peptide.shaker.txt)
)

**Comment by vipulbatra1985** [comment] 2021-07-29 06:36
Please reply.

**Comment by vipulbatra1985** [comment] 2021-07-29 07:31
How to proceed further?

**Comment by hbarsnes** [comment] 2021-07-29 21:22
I will have a closer look as soon as I get back to work after next week.

**Comment by vipulbatra1985** [comment] 2021-07-30 04:27
Okay, I will wait till then and am very eager to get the issue resolved at the earliest. Thanks.

**Comment by vipulbatra1985** [comment] 2021-08-12 07:37
Are you back yet?

**Comment by hbarsnes** [comment] 2021-08-12 13:44
I've tried upgrading some of the libraries we use when interacting with the database backend. Can you try this beta release and tell me if it makes any difference? 

PeptideShaker v2.0.36-beta: http://vedlegg.uib.no/?id=806246c15c618c93137097f5fea43c42

**Comment by vipulbatra1985** [comment] 2021-08-13 11:25
I cannot access the link since nothing happens on clicking the hyperlink.

**Comment by hbarsnes** [comment] 2021-08-13 12:28
Strange. In any case, I've now released a new official version with the same fixes, so you can try that one instead.

**Comment by vipulbatra1985** [comment] 2021-08-16 09:54
I tried, but no avail. PFA the bug reports
[PeptideShaker 2.1.0 log.txt](https://github.com/compomics/searchgui/files/6991404/PeptideShaker.2.1.0.log.txt)
[SearchGUI 4.1.0 log.txt](https://github.com/compomics/searchgui/files/6991406/SearchGUI.4.1.0.log.txt)

**Comment by vipulbatra1985** [comment] 2021-08-16 10:10
In fact, it has been more than a year since this issue cropped up and I have not been able to use this wonderful tool to analyze my proteomics data. Please help to resolve the issue once and for all.

**Comment by hbarsnes** [comment] 2021-08-16 10:57
Would it be possible for you to share the dataset so that we can try to reproduce the issue on our end and thus hopefully get to the root of the issue? If you share your SearchGUI zip file we should have all we need.

Note that we would like nothing more than to solve this issue once and for all ourselves as well. But the fact that it has taken this long sadly means that we have not been able to come up with a fix. I therefore cannot guarantee that we will be able to do so in the near future either...

**Comment by hbarsnes** [comment] 2021-08-16 13:57
Hi again. I just released PeptideShaker 2.1.1 which should hopefully solve the problem. At least the specific error in your recent log file. Please give it a go and let me know.

**Comment by vipulbatra1985** [comment] 2021-08-17 04:09
Please give me your email address. I will share the searchGUI zip file.

**Comment by vipulbatra1985** [comment] 2021-08-17 04:15
[report_SearchGUI_17.8.21.txt](https://github.com/compomics/searchgui/files/6996996/report_SearchGUI_17.8.21.txt)

The search ended abruptly. I tried to open the results in peptide shaker, nevertheless, it failed. Again. PFA
[peptideshaker.txt](https://github.com/compomics/searchgui/files/6997018/peptideshaker.txt)

**Comment by hbarsnes** [comment] 2021-08-17 09:08
You can share the SearchGUI zip file with me at harald.barsnes@gmail.com

**Comment by hbarsnes** [comment] 2021-08-17 09:09
BTW, can you also share the PeptideShaker log file for the last attempt?

**Comment by vipulbatra1985** [comment] 2021-08-17 10:38
PFA the log file
[PeptideShaker 2.1.1 log.txt](https://github.com/compomics/searchgui/files/6999230/PeptideShaker.2.1.1.log.txt)

**Comment by hbarsnes** [comment] 2021-08-17 11:21
Thanks for sharing the SearchGUI zip file. However, I will also need the mzML and FASTA file in order to load the data. Can you share these as well?

**Comment by vipulbatra1985** [comment] 2021-08-17 12:08
Shared.

**Comment by hbarsnes** [comment] 2021-08-17 12:24
Thanks again. Trying to load the data now.

**Comment by hbarsnes** [comment] 2021-08-17 17:07
I've tried a couple of different fixes without full success so far, but I will keep trying when I get the chance.

However, I had no problems loading your data in PeptideShaker when I increased the memory from 8GB to 16GB. I will send you the zipped project directly via email.

I see that you are using a total of seven search engines at the same time btw. Generally there is not much point in using more than 2-3 unless your main objective is to compare search engines. I'm pretty sure that if you reduce the number of search engines you should be able to also load the data with 8GB of memory.

**Comment by vipulbatra1985** [comment] 2021-08-22 07:03
It worked. Finally. After so so long. Though I can't see the .psdb files, I can open the zip file in peptide shaker. Thank you so so much Harold. I really appreciate it.

**Comment by hbarsnes** [comment] 2021-08-23 12:32
Great! I will then close the issue. But feel free to open a new one if you have more questions in the future.

**Closed by hbarsnes** 2021-08-23 12:32 UTC
Labels: help wanted
