### ISSUE TITLE
X!Tandem Vengeance kicks out all spectra missing the precursor charge state tag

### ISSUE THREAD

**Issue by 1Moe** [compomics/searchgui#95] opened 2016-03-03 03:08 UTC
Hi all :)

It would be great to get some help on the following issue:
I've got the newest version of SearchGUI 2.7.0 and a previous version 2.6.5.
With the new version 2.7.0, my mgf files don't get accepted by the 2015 X!Tandem search engine (Vengeance), whereas 2.6.5 (using X!tandem Sledgehammer) has no complaints. 

SearchGUI 2.7.0 says that "No input spectra met the acceptance criteria." and finishes the search. 
Searching with Comet and Andromeda worked fine in 2.7.0!

Below are log files of SearchGUI 2.6.5 followed by 2.7.0 using the identical mgf file.
Here is a link to the zipped mgf and wiff files (Filename: MGF_WIFF_test.zip).
https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM

Cheers
Moe

***2.6.5***
Thu Mar 03 14:12:18 NZDT 2016        Indexing spectrum files.
Thu Mar 03 14:12:18 NZDT 2016        Extracting search settings.

Thu Mar 03 14:12:18 NZDT 2016        Processing 15016_16_E1_DDA_1_17.mgf with X!Tandem.

X! TANDEM Sledgehammer (2013.09.01.1)

Loading spectra| (mgf).... loaded.
Spectra matching criteria = 7901
Starting threads .|.|.|. started.
Computing models:
	Spectrum-to-sequence matching process in 
	waiting for 234 done.

	sequences modelled = 40 ks
Model refinement:

	waiting for 234 done.

Merging results:
	from 2.3.4.

Creating report:
	initial calculations  ..... done.
	sorting  ..... done.
	finding repeats ..... done.
	evaluating results ..... done.
	calculating expectations ..... done.
	writing results ..... done.

Valid models = 7691

Thu Mar 03 14:13:07 NZDT 2016        X!Tandem finished for C:\Exp4_RedAlk2\15016_16_E1_DDA_1_17.mgf (48.973 seconds).

Thu Mar 03 14:13:07 NZDT 2016        Zipping output files.

Thu Mar 03 14:13:08 NZDT 2016        Search Completed (49.703 seconds).

***2.7.0***

Thu Mar 03 14:05:07 NZDT 2016        Indexing spectrum files.
Thu Mar 03 14:05:07 NZDT 2016        Extracting search settings.

Thu Mar 03 14:05:07 NZDT 2016        Processing 15016_16_E1_DDA_1_17.mgf with X!Tandem.

X! TANDEM Vengeance (2015.12.15.2)

Loading spectra| (mgf).... loaded.
No input spectra met the acceptance criteria.

Thu Mar 03 14:05:14 NZDT 2016        X!Tandem finished for C:\Exp4_RedAlk2\15016_16_E1_DDA_1_17.mgf (6.881 seconds).

Thu Mar 03 14:05:14 NZDT 2016        Could not rename X!Tandem result for 15016_16_E1_DDA_1_17.mgf.
Thu Mar 03 14:05:14 NZDT 2016        Could not find X!Tandem result file for 15016_16_E1_DDA_1_17.mgf.
Thu Mar 03 14:05:14 NZDT 2016        Zipping output files.

Thu Mar 03 14:05:14 NZDT 2016        Search Completed (6.94 seconds).

Cheers
Moe

**Comment by hbarsnes** [comment] 2016-03-03 12:19
Hi Moe,

Thanks for telling us about this. I think the problem is that X! Tandem started to kick out spectra that do not have the precursor charge set. I know that they talked about implementing this in future versions, but I did not see anything about it in the release notes. 

Here's the reply I got when asking about this a while back:

> The parent ion mass without a charge is an error in the file. X! Tandem does not spend much time checking for file format errors and tries not to simply stop when an error is encountered. Thanks for pointing out this problem: the next version will discard all spectra in MGF format that do not have parent ion charges specified.

Not really sure how to handle this. I guess we could add a feature that adds charge tags in the mgf file if they are not there, but not sure which charge(s) we should add in this case?

Are all wiff file conversions missing the precursor charge state in the mgf file?

Best regards,
Harald

**Comment by 1Moe** [comment] 2016-03-04 01:40
Hi Harald,

thanks for your helpful reply! The conversions results (from wiff to mgf) depend on the converter choice. 

1) If I use MSconvert from SearchGui or qtofpeakpicker from the commandline, all precursors have missing charge states in the mgf file. X!tandem vengeance doesn't work with these mgf files. X!tandem sledgehammer works.

2) If I use the AB_SCIEX_MS_Converter, most (~80%) of the precursors have associated charge states in the mgf file. X!tandem vengeance and sledgehammer work with these mgf files.

You can download the example files here (zipped wiff, wiff.scan and the 3 different mgf files using 3different converters):https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM

Not sure why this happens, the qtofpeakpicker is apparently better than the sciex peak picker for centroiding according to Schubert et al. 2015 (http://www.ncbi.nlm.nih.gov/pubmed/25675208)

best wishes and thanks for the great support!
Moe

**Comment by hbarsnes** [comment] 2016-03-04 12:06
Ho Moe,

Maybe it would be an idea that you contact the X! Tandem developers and try to convince them to change their policy of kicking out spectra missing the precursor charge? You can do this by sending an e-mail to contact@thegpm.org. Hopefully you will have better luck than me...

Best regards,
Harald

**Comment by 1Moe** [comment] 2016-03-06 23:21
Thanks Harald,
I've emaild the gpm team today and will keep you updated. If there is no charge state info, Mascot typically searches those spectra for 2-3-4-5 (or whatever you select as an option). Is there something equivalent/possible where you could force searching those spectra with no charge state info? I also don't know which charge state I would assign. 
From sample 1 (1Sciex.mgf) I looked at the frequency of charge states. See table below.
Charge	Frequency
1	0
2	3512
3	1578
4	914
5	273
6	97
7	12
8	3
9	0
10	0
More	0

cheers
Moe

**Comment by hbarsnes** [comment] 2016-03-07 13:00
Hi Moe,

> If there is no charge state info, Mascot typically searches those spectra for 2-3-4-5 (or whatever you select as an option). Is there something equivalent/possible where you could force searching those spectra with no charge state info?

I'm afraid we cannot force the search engines to do things they don't want to do. It would clearly be best if the search engines where able to handle missing charges on their own, preferably checking a range of possible charges provided by the user (as you indicate for Mascot). But if this is not the case the only option we have would be to alter the mgf files and add the wanted charge range for the spectra where it is missing. The problem is that we would then have to change the mgf file (or most likely make a new mgf file), and thus add an additional step that ought to not be required in the first place. But if this is our only option...

Best regards,
Harald

**Comment by 1Moe** [comment] 2016-03-07 21:33
Thanks Harald
yeah, sounds like a good idea to enable the option of testing a range of charge states. Also agree that it would be a bad idea to alter the mgf files. I'm not sure that the file MSconversion issue for wiff files is being addressed in the near future. I got this info from the ProteoWizard support when I asked about the charge state issue:

> This is simply because Sciex's API does not calculate the charge state for us (and it's not stored in the file). Their standalone converter does calculate it, and also uses the Protein Pilot peak picker which is better than the one they give us in their API.

Not exactly sure what this means, my guess is that the ProteoWizard guys are limited by what Sciex has supplied them with. In the meantime I'll use the AB Sciex data converter which carries through the charge state info to the mgf files (but isn't as good at peak picking as qtofpeakpicker). This way I can at least continue to use X!tandem vengeance.

I know it's a bit backwards but is there a way for me to choose between vengeance and sledgehammer in SearchGUI?

**Comment by hbarsnes** [comment] 2016-03-09 12:02
Hi Moe,

> I know it's a bit backwards but is there a way for me to choose between vengeance and sledgehammer in SearchGUI?

You can choose all the search engine installation folders via the Edit > Search Engines. So if you still have an old SearchGUI installation with the previous X! Tandem version you can select this folder here. Note that it will be reset when upgrading to a new SearchGUI version.

We are working on a fix for the missing precursor charges, it will hopefully be out later this week. It will consist of making a new mgf file where a user decided charge range is added for the spectra missing this information. This is basically how most search engines treat missing charges anyway.

Best regards,
Harald

**Comment by 1Moe** [comment] 2016-03-10 20:57
Thanks Harald,
again, excellent support, much appreciated.
Cheers
Moe

**Comment by hbarsnes** [comment] 2016-03-10 21:00
Hi Moe,

Did you get any reply from X! Tandem btw?

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-03-16 18:51
Hi Moe,

In the just released SearchGUI version you can now tell SearchGUI to check your mgf file for missing precursor charges and replace any missing values with a user defined charge range. You'll find the options via the Advanced Settings menu option in the main SearchGUI dialog.

This allows you to use the latest X! Tandem version to process your mgf files. Not sure how the missing charges will affect the end results though, as it would of course be preferable to have the actual precursor charges available instead of adding a default range. So would be great if you could do some tests and compare the old and new X! Tandem versions? As far as I could tell the results were very similar.

Closing this issue now, but do feel free to still add any additional comments related to the issue. We'll still read them. But if you come across new problems please open a new issue as this makes it easier for us to stay on top of new issues.

Best regards,
Harald

**Closed by hbarsnes** 2016-03-16 18:51 UTC
Labels: help wanted
