### ISSUE TITLE
Resource path settings for conda version

### ISSUE THREAD

**Issue by mglubber** [compomics/searchgui#211] opened 2019-04-12 02:11 UTC
When SearchGUI is installed through conda on Ubuntu 16.04, many of the settings/configurations are still saved to the user's home directory (i.e. `/home/$USER/.compomics`). Can this be moved to the conda environment where SearchGUI is installed to make managing different environments/versions easier?

**Comment by CarlosHorro** [comment] 2019-04-13 10:42
Hi,

Well, doing it by default may give some problems. As an example, one of the main uses of the conda package is to be installed as a Galaxy tool dependency. Installing user-dependent content into the SearchGUI's Conda folder would cause many users sharing their info, which is undesired.
But, when running the package, it may be possible to add the option "-temp" with the desired folder to place all custom info...

**Comment by bernt-matthias** [comment] 2020-12-18 14:39
@CarlosHorro Its also undesirable in the Galaxy environment. Galaxy can be configured such that the jobs run with the credentials of the real users (the default in that there is a special user starting all jobs). Then users having the config dir (because they may use the tool also on the command line) might get different results if they change the config or in comparison to other user's results. 

This contradicts the reproducibility assumption of galaxy.

But I think in the Galaxy tool we set `$HOME` to a temp dir. Which might also be a good workaround for @mglubber

**Comment by hbarsnes** [comment] 2020-12-22 00:30
Note that it is possible to alter where most/all of the SearchGUI settings and temp files are stored. Either via the command line (https://github.com/compomics/searchgui/wiki/SearchCLI#pathsettingscli) or via the GUI (Edit > Resource Settings).

@CarlosHorro and @bernt-matthias I was assuming that this option was being used when running SearchGUI both via conda and Galaxy?

**Comment by bernt-matthias** [comment] 2020-12-22 11:02
> I was assuming that this option was being used when running SearchGUI both via conda and Galaxy?

I think this is applied in the SearchGUI Galaxy wrapper, but not automatically in conda (users would need to call SearchCLI manually). 

Wondering how this applies to other software like MPA?

**Comment by hbarsnes** [comment] 2020-12-22 11:43
> Wondering how this applies to other software like MPA?

No idea. Our temp file settings only affect SearchGUI and PeptideShaker.

**Comment by CarlosHorro** [comment] 2021-03-17 13:03
This has been automatically managed in recent Conda packages using the TEMP variable, so I close this issue.

**Closed by CarlosHorro** 2021-03-17 13:03 UTC
Labels: help wanted
