### ISSUE TITLE
Comet search - takes long and results do not open in PeptideShaker

### ISSUE THREAD

**Issue by PRprog** [compomics/searchgui#240] opened 2020-05-09 13:09 UTC
Hi,
recently I tried a simple search of a QExactive raw file of a BSA standard (SearchGUI 3.3.19 + Peptide Shaker 1.16.45, on a PC with Windows 10, Java 64bit). Among others I tried to search with Comet and it took very long on my laptop (~2 hours 30 min) in comparison with other tools (e.g. OMSSA, X!Tandem - lest than 2 min). Moreover, when finished, the results (.cpsx file) could not be open with the error
>It looks like another instance of PeptideShaker is still connected to the file

however no other instance of PeptideShaker was open.
Some log files etc.:
[https://filesender.cesnet.cz/?s=download&token=13651499-643f-d848-547f-0ca73e3272b2](https://filesender.cesnet.cz/?s=download&token=13651499-643f-d848-547f-0ca73e3272b2)
where
- ...results_06d.zip - the SearchGUI results
- matches.zip - temp directory from SearchGUI
- PeptideShaker.log, SearchGUI.log, SearchGUI_Comet_log.txt - log files
- SearchGUI_Peptide_Shaker_Comet_error.jpg - screenshot of the PeptideShaker error

I have also tried to "update" the Comet binaries in the installation of SearchGUI by replacing the corresponding exe file by the newest version of Comet (2019.01 rev. 5), however I always get the error
>Comet version 2019.01 rev. 5
The comet.params file is from version 2018.01
Please update your comet.params file.  You can generate
a new parameters file using "comet -p"
...
Thu May 07 22:11:58 CEST 2020        Search Canceled!

I have also tried to create a new parameters file, however this gets always overwritten when SearchGUI starts to the old parameters version. How can I actually update the executable of an engine in SearchGUI (if it is easily possible)?

Thank you for your help!
Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-05-09 15:03
Hi Pavel,

I do not see why the Comet search should take that long. Perhaps it is somehow confused by the combination of variable modifications? Don't really see why that should be the case though. Did you change any of the advanced Comet parameters btw?

Would it be possible for you to also share the spectrum and FASTA files so that I can try to reproduce the error?

As for the PeptideShaker error, I think this should be solved by trying to reload the data directly in PeptideShaker?

> I have also tried to "update" the Comet binaries in the installation of SearchGUI by replacing the corresponding exe file by the newest version of Comet (2019.01 rev. 5).

I'm afraid this is not possible as Comet requires the version number to be hardcoded in its parameter file, which has resulted in us having to update this in our code every time we update Comet. There is currently no way in which you can edit this yourself as it will be overwritten by SearchGUI.

> How can I actually update the executable of an engine in SearchGUI (if it is easily possible)?

You can do it they way you tried for most of the other search engines, but not for Comet given the reasons explained above. But usually an update also requires that we add support for new search engine parameters so it is not really recommended to update "manually".

We are working on new beta releases of both SearchGUI and PeptideShaker with updated versions of many of the search engines. If you share your spectrum and FASTA files I can quickly test if updating to Comet version 2019.01 rev. 5 makes any difference for your specific example.

Best regards,
Harald

**Comment by PRprog** [comment] 2020-05-09 15:49
Hi Harald,
it is also not clear to me why the Comet search takes that long. I do not think that the number of variable modifications is that high (because many of them do not occur that often like N-terminal Gln), but it may really depend on the way the Comet process data. I did not change anything in the Comet engine settings.
I send you to your email the link to the raw data and FASTA DB for testing. Could you also try to test the Tide DB search? I always ended up with some error, see the results with some log files
[https://filesender.cesnet.cz/?s=download&token=d9e6c076-564d-9853-2d36-56e4f07f2a1f](https://filesender.cesnet.cz/?s=download&token=d9e6c076-564d-9853-2d36-56e4f07f2a1f)
Regarding the PeptideShaker error, reloading in PeptideShaker did not help in the Comet case (although in the case of another engine - I guess it was X!Tandem - it helped).
It is a pity that the version of Comet has to be hardcoded in the SearchGUI. I can understand that the update has to be somehow in agreement with the new parameters coming with the engine.
Thank you for your help!
Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-05-09 17:22
Hi Pavel,

I see no obvious reason why Comet would take long. Do not see any real difference when updating to the latest Comet version though. I'd recommend contacting the Comet developers directly at http://groups.google.com/group/comet-ms. If you share the Comet command line and the Comet parameter file (SearchGUI-3.3.19\resources\Comet\windows\windows_64bit\comet.params) they should be able to have a closer look without having to run it via SearchGUI.

For the Tide issue, I can only reproduce the error if I use the raw file as input. Everything is ok if I use the mgf as input. I will look into it and come up with a fix. Perhaps you can stick with the mgf as input for Tide in the meantime?

Best regards,
Harald

**Comment by hbarsnes** [comment] 2020-05-09 18:42
Hi again,

I just released SearchGUI v3.3.20 which should solve the Tide raw file issue. Please let me know if this is not the case.

Best regards,
Harald

**Comment by PRprog** [comment] 2020-05-10 15:42
Hi Harald,
thank you for the SearchGUI corrections and the new version. The Tide search works now as expected, and similarly the multiple searches work OK. Thank you!
So the only engine not working now for me is the Comet. I have tried it again - the results with some additional information are available here:
[https://filesender.cesnet.cz/?s=download&token=abb275f2-713e-be66-e684-f34e91dbede6](https://filesender.cesnet.cz/?s=download&token=abb275f2-713e-be66-e684-f34e91dbede6)
The problems are still the same:
- the search takes too long -> I will try to submit the issue to the Comet discussion group
- the SearchGUI output does not open in PeptideShaker - screenshot "Comet_PeptideShaker_results_opening.jpg"
- the SearchGUI output does not open in PeptideShaker also when trying to reopen it manually in PeptideShaker - screenshot "Comet_PeptideShaker_results_reopening.jpg"

Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-05-10 17:17
Hi Pavel,

> the search takes too long -> I will try to submit the issue to the Comet discussion group

It will be interesting to hear what they have to say. I still haven't been able to think of any good reasons why Comet would take this long on such a small dataset.

> the SearchGUI output does not open in PeptideShaker - screenshot "Comet_PeptideShaker_results_opening.jpg"

Try emptying the folder C:\Users\rehulkap\Documents\DBsearch\PeptideShaker-1.16.45\resources\matches before running SearchGUI. If you cannot empty this folder it means that another instance if PeptideShaker is still running in the background. You may then have to cancel the process/processes from the task manager.

> the SearchGUI output does not open in PeptideShaker also when trying to reopen it manually in PeptideShaker - screenshot "Comet_PeptideShaker_results_reopening.jpg"

This will not work. If the cpsx file is corrupted during creation it cannot be opened in PeptideShaker. Try instead to reprocess the searchgui_out.zip directly in the PeptideShaker. This worked fine for me for your dataset.

Best regards,
Harald

**Comment by PRprog** [comment] 2020-05-11 08:54
Hi Harald,
> > the SearchGUI output does not open in PeptideShaker - screenshot "Comet_PeptideShaker_results_opening.jpg"

> Try emptying the folder C:\Users\rehulkap\Documents\DBsearch\PeptideShaker-1.16.45\resources\matches before running SearchGUI. If you cannot empty this folder it means that another instance if PeptideShaker is still running in the background. You may then have to cancel the process/processes from the task manager.

I have checked the "matches" directory. It is empty, there are not even any hidden files. The computer was just restarted (no forgotten PeptideShaker processes should remain in the memory). And the error is the same - the PeptideShaker output created from SearchGUI (only!) for the Comet DB search cannot be open.

Reprocessing of the SearchGUI output in PeptideShaker works. However, I do not understand, why a peptide with apparently no matched fragment ions results in a confidence value 100 and the corresponding protein as well:
![PS_01](https://user-images.githubusercontent.com/63408887/81542651-4b2e3e80-9375-11ea-9f0d-4048234cdf45.jpg)
But this may be again the issue with the Comet engine?
Similar question is why the identification of BSA is doubtful when so many peptides are matched there. But this may be a result of my beginner level of the work with PeptideShaker, I guess.

Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-05-11 09:32
Hi Pavel,

> I do not understand, why a peptide with apparently no matched fragment ions results in a confidence value 100 and the corresponding protein as well. But this may be again the issue with the Comet engine?

There are matched fragment ions, they are just hidden. Click View > Spectrum Sliders. Two sliders will then appear next to the spectrum where the bottom one controls the annotation level relative to the most intense peak. If you move it down toward 0% you'll see some of the peaks becoming annotated.

Usually you'll see more peaks annotated at the default 75% level, but for this specific spectrum the peak intensities are very low and the most intense peak is not annotated itself. The rational behind hiding the low intensity peaks (relative to the most intense one) is generally that these often represent noise and make it harder to interpret the most interesting peak annotations.

> Similar question is why the identification of BSA is doubtful when so many peptides are matched there. 

If you click the yellow warning triangle you will see information about why the given protein/peptide/PSM was categorized as doubtful. For the case of BSA, there are simply no confident peptides or spectra.

Overall the statistical analysis is problematic for this dataset given that there are so few hits. The warnings therefore indicate that the (statistical) analysis generally cannot be trusted.

For more details on the statistical analysis in PeptideShaker please see the tutorial material.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2020-05-11 20:59
Hi Pavel,

Just wanted to confirm that Jimmy's guess was not that far off. With Comet version "2019.01 rev. 5" I'm able to complete your search in 17 minutes 40 seconds. I guess I simply did not wait long enough when testing this version earlier as I thought that it in any case was taking way too long. (This is without the suggested merge of the two PTMs btw, as this is generally not supported in SearchGUI.)

The updated Comet version has already been included in the next major SearchGUI release, but I cannot yet tell you when it will become available as we're having some other issues that need to be sorted out first.

But I assume that you can stick with the other search engines in the meantime?

Best regards,
Harald

**Comment by PRprog** [comment] 2020-05-12 15:06
Hi Harald,

yes, Jimmy was right, the newer version of Comet really worked better, however I am puzzled by Comet's behaviour anyway:
[https://groups.google.com/forum/#!topic/comet-ms/rR5VZLW9gLc](https://groups.google.com/forum/#!topic/comet-ms/rR5VZLW9gLc)
Briefly, the DB search takes too long when trying to employ variable modifications. And I do not see any reason why. :-( But Jimmy may explain it.

> The updated Comet version has already been included in the next major SearchGUI release...
But I assume that you can stick with the other search engines in the meantime?

Yes, this is not a problem for me, thank you for updating the Comet (and other engines too)!
 
When trying to "update" Comet version, I found the beta versions of SearchGUI and PeptideShaker
`Fri Feb 21 16:54:03 CET 2020: PeptideShaker version 2.0.0-beta.`
`searchgui.version=4.0.0-beta`
and I have a few remarks:
- several suggestions about SearchGUI version 3.3.20 discussed in [https://github.com/compomics/searchgui/issues/241](https://github.com/compomics/searchgui/issues/241) may apply for the beta version too
- the error about repeated processing of the raw file (corrected in SearchGUI 3.3.20) is present in the beta version as well
- sometimes PeptideShaker does not open the results with an error
`Please verify that the version used to create file is compatible with your version of PeptideShaker`
and when closing the PeptideShaker, another error message appears
`Failed to empty the database folder ...\matches`
- in the window for edition of search parameters, there is a parameter called "Isotopes". I do not exactly know what it exactly means, but I presume that here you can allow to take into account theoretically not only the monoisotopic peak for the precursor, but also the second isotopic peak as the one which was probably fragmented in the instrument (due to the incorrect experimental identification of monoisotopic peak). Here I tried to provide the range from "0" to "0" (like I do not want to consider second isotopes for ID search). And although this was possible to do in the SearchGUI 3.3.20, this failed in the case of beta version of SearchGUI, the parameters could not be saved and the situation looked like this:
![PS_03](https://user-images.githubusercontent.com/63408887/81706240-2f5b9300-9470-11ea-8838-20bea66cec71.jpg)
I guess it should not produce an error when putting "0" into both limits for "Isotopes". Do I understand this right?

A note to the tutorials: in my Firefox I could not open e.g. the file
[https://drive.google.com/file/d/0B4sW8rLWPbRyaDBXMDVXOWVaUkk/view](https://drive.google.com/file/d/0B4sW8rLWPbRyaDBXMDVXOWVaUkk/view)
however I could open it in Opera, where I was logged into Google. It may be that my addons in Firefox block opening of that pdf document for some reasons, but could you check on this? I.e. if the document is freely available or only available for those logged under a Google account.

Thank you for your help!

Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-05-12 16:49
Hi Pavel,

> several suggestions about SearchGUI version 3.3.20 discussed in #241 may apply for the beta version too

Yup, all of the issues will be implemented in the beta version as well. Or rather, for some of them, only in the beta version.

> the error about repeated processing of the raw file (corrected in SearchGUI 3.3.20) is present in the beta version as well

The beta version has not been updated in a while due to other unsolved issues, but this error has already been corrected in the code.

> sometimes PeptideShaker does not open the results with an error

At the moment you cannot open any saved projects in the beta version: https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues/47. The main reason why I did not send you the link to the beta versions in the first place. :)

> I guess it should not produce an error when putting "0" into both limits for "Isotopes". Do I understand this right?

Yup, it was a bug that has already been fixed a while back, but not after the current beta version was deployed.

> It may be that my addons in Firefox block opening of that pdf document for some reasons, but could you check on this?

There should be no need to log in. Not sure why Firefox does not want to display the file directly. Maybe it has to do with the size of the PDF? But you can always click the download button to get the PDF and then open it locally?

Best regards,
Harald

**Comment by PRprog** [comment] 2020-05-14 08:18
Hi Harald,

thank you for all the comments and corrections!
>> sometimes PeptideShaker does not open the results with an error

>At the moment you cannot open any saved projects in the beta version: compomics/peptide-shaker-2.0-issue-tracker#47. The main reason why I did not send you the link to the beta versions in the first place. :)

I have looked at the mentioned issue, and I can only remember that the following error after not opening the PeptideShaker result was that the "matches" directory could not be emptied and the file there had the "psdb" extension (if I remember correctly).

>> It may be that my addons in Firefox block opening of that pdf document for some reasons, but could you check on this?

> There should be no need to log in. Not sure why Firefox does not want to display the file directly. Maybe it has to do with the size of the PDF? But you can always click the download button to get the PDF and then open it locally?

Suprisingly, now it works (even if it is slow to open the pdf document). Sorry for reporting an irreproducible (and "self-healing") error :-(

Best regards,
Pavel

**Comment by hbarsnes** [comment] 2020-11-04 15:01
The feature requests should hopefully be implemented as wanted in the new release that has just been made available. It also includes the latest version of Comet which should address those issues as well. If this is not the case, please let us know and we'll reopen the issue.

**Closed by hbarsnes** 2020-11-04 15:01 UTC
Labels: help wanted
