### ISSUE TITLE
Error searching with Andromeda

### ISSUE THREAD

**Issue by armonyG** [compomics/searchgui#122] opened 2016-10-26 14:56 UTC
Hello, when I try to search with Andromeda i get an error:

![andromeda error](https://cloud.githubusercontent.com/assets/23078645/19728727/2d6bdcaa-9b9d-11e6-8bdf-0bf80841d2c5.png)

The report file say:

> Wed Oct 26 16:47:26 IDT 2016        Processing QEP2_DFA_ECM_CL_pellet_BS3_1_051016.mgf with Andromeda.
> 
> Start Search.
> 
> Unhandled Exception: System.Exception: Exception during execution of external process: 8116
>    at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternal(Int32 taskIndex, Int32 threadIndex)
>    at BaseLibS.Util.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
>    at BaseLibS.Util.WorkDispatcher.Work(Object threadIndex)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)
> 
> Wed Oct 26 16:53:52 IDT 2016        Andromeda finished for QEP2_DFA_ECM_CL_pellet_BS3_1_051016.apl (6 minutes 385 seconds).
> 
> Wed Oct 26 16:53:52 IDT 2016        Could not find Andromeda .res file for QEP2_DFA_ECM_CL_pellet_BS3_1_051016.mgf.

Haven't checked the rest but X! Tandem and OMSSA works.

Gadi

**Comment by mvaudel** [comment] 2016-10-26 15:03
Hi,

It seems like an internal process of Andromeda has an issue with the enzyme used. Which one was it?

Best regards,

Marc

**Comment by armonyG** [comment] 2016-10-26 15:09
The enzyme is Trypsin, no P rule
![enzyme](https://cloud.githubusercontent.com/assets/23078645/19731815/575f9916-9ba7-11e6-91ca-94423db10d40.png)

**Comment by armonyG** [comment] 2016-10-27 10:18
Using regular trypsin works

**Comment by hbarsnes** [comment] 2016-10-27 14:14
Hi,

The problem seems to be the comma in the enzyme name, as Andromeda supports the input of multiple enzymes, (presumably) separated by comma. The enzyme name has already been altered for the next PeptideShaker release which seems to solve the problem. In the meantime please use one or more of the other search engines supported in SearchGUI. 

We'll let you know when the new PeptideShaker version is available.

Best regards,
Harald

**Comment by armonyG** [comment] 2016-10-27 14:15
OK, Thank you very much.

**Comment by hbarsnes** [comment] 2016-10-27 14:42
As the problem is not fixed in the current release we prefer to keep the issue open in case other users have the same problem. :)

**Comment by hbarsnes** [comment] 2016-12-04 13:07
Hi,

SearchGUI v3.2.0 has now been released which should fix the problem with the enzymes. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Closed by hbarsnes** 2016-12-04 13:07 UTC
Labels: help wanted
